#!/usr/bin/env python3
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
COMPARISON_SOURCES = [
    ROOT / 'app' / 'Main.hs',
    ROOT / 'app' / 'App' / 'ComparisonRunner.hs',
]
OUTPUT = ROOT / 'docs' / 'runnable-comparisons.md'

comparison_pattern = re.compile(r'(?:putStrLn|printComparisonHeader)\s+"(Comparison\s+\d+:\s+[^"]+)"')
comparisons = []
source_path = None
for candidate in COMPARISON_SOURCES:
    for line in candidate.read_text().splitlines():
        match = comparison_pattern.search(line)
        if match:
            if source_path is None:
                source_path = candidate
            comparisons.append(match.group(1))
    if comparisons:
        break

if not comparisons:
    searched = ', '.join(str(path.relative_to(ROOT)) for path in COMPARISON_SOURCES)
    raise SystemExit(f'No comparison headings found in any of: {searched}')

lines = [
    '# Runnable Comparisons',
    '',
    '<!-- Generated by scripts/generate-runnable-comparisons.py. Do not edit by hand. -->',
    '',
    f'This page mirrors the categories printed by `/{source_path.relative_to(ROOT).as_posix()}`.'.replace('`/', '`/Users/scottpeterson/Dev/PurelyFunctional/HaskellDemo/'),
    '',
    'Run the executable with:',
    '',
    '```bash',
    'cabal run HaskellDemo',
    '```',
    '',
    '## Output Categories',
    '',
]
for idx, comparison in enumerate(comparisons, start=1):
    lines.append(f'{idx}. `{comparison}`')
lines += [
    '',
    '## Best Matching Docs Pages',
    '',
    '- deepest feature workflows:',
    '  - [End-to-End Registration](triads/end-to-end-registration.md)',
    '  - [Password Reset Feature](triads/password-reset.md)',
    '  - [Configuration Startup Feature](triads/configuration-startup.md)',
    '- architecture overview:',
    '  - [Comparing With C#](architecture/comparing-with-csharp.md)',
    '  - [Learning Path](architecture/learning-path.md)',
    '- contribution flow:',
    '  - [Contributing](contributing.md)',
    '  - [Propose A Triad](triads/propose-a-triad.md)',
    '',
    '## Why This Page Exists',
    '',
    'The docs site now has a learning path and deeper triad guidance, but this page gives a direct index back to the exact output categories a reader will see when they run the executable. That makes it easier to jump between terminal output, code, and docs without translating names by hand.',
    '',
    '## Regenerating This Page',
    '',
    'Run:',
    '',
    '```bash',
    'python3 scripts/generate-runnable-comparisons.py',
    '```',
    '',
    'after changing the comparison headings in the comparison runner source file.',
]
OUTPUT.write_text('\n'.join(lines) + '\n')
