#!/usr/bin/env python3
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
MAIN = ROOT / 'app' / 'Main.hs'
OUTPUT = ROOT / 'docs' / 'runnable-comparisons.md'

comparison_pattern = re.compile(r'putStrLn\s+"(Comparison\s+\d+:\s+[^"]+)"')
comparisons = []
for line in MAIN.read_text().splitlines():
    match = comparison_pattern.search(line)
    if match:
        comparisons.append(match.group(1))

if not comparisons:
    raise SystemExit('No comparison headings found in app/Main.hs')

lines = [
    '# Runnable Comparisons',
    '',
    '<!-- Generated by scripts/generate-runnable-comparisons.py. Do not edit by hand. -->',
    '',
    'This page mirrors the categories printed by `/Users/scottpeterson/Dev/PurelyFunctional/HaskellDemo/app/Main.hs`.',
    '',
    'Run the executable with:',
    '',
    '```bash',
    'cabal run HaskellDemo',
    '```',
    '',
    '## Output Categories',
    '',
]
for idx, comparison in enumerate(comparisons, start=1):
    lines.append(f'{idx}. `{comparison}`')
lines += [
    '',
    '## Best Matching Docs Pages',
    '',
    '- deepest feature workflows:',
    '  - [End-to-End Registration](triads/end-to-end-registration.md)',
    '  - [Password Reset Feature](triads/password-reset.md)',
    '- architecture overview:',
    '  - [Comparing With C#](architecture/comparing-with-csharp.md)',
    '  - [Learning Path](architecture/learning-path.md)',
    '- contribution flow:',
    '  - [Contributing](contributing.md)',
    '  - [Propose A Triad](triads/propose-a-triad.md)',
    '',
    '## Why This Page Exists',
    '',
    'The docs site now has a learning path and deeper triad guidance, but this page gives a direct index back to the exact output categories a reader will see when they run the executable. That makes it easier to jump between terminal output, code, and docs without translating names by hand.',
    '',
    '## Regenerating This Page',
    '',
    'Run:',
    '',
    '```bash',
    'python3 scripts/generate-runnable-comparisons.py',
    '```',
    '',
    'after changing the comparison headings in `/Users/scottpeterson/Dev/PurelyFunctional/HaskellDemo/app/Main.hs`.',
]
OUTPUT.write_text('\n'.join(lines) + '\n')
